<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zanzibar</name>
   <tag></tag>
   <elementGuidId>2af1f720-3a00-4b24-9d30-319cce7c5a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/main[1]/form[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/div[1]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body/main[1]/form[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/div[1]/div[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/main[1]/form[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/div[1]/div[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
